DROP TABLE CHECKPOINTS;
DROP TABLE CHECKPOINT_BLOBS;
DROP TABLE CHECKPOINT_MIGRATIONS;
DROP TABLE CHECKPOINT_WRITES;



-- BEGIN
--   EXECUTE IMMEDIATE
--     q'[
--       ALTER TABLE checkpoint_writes
--         ADD task_path VARCHAR2(1000) DEFAULT ''
--     ]';
-- EXCEPTION
--   WHEN OTHERS THEN
--     IF SQLCODE = -1430 THEN
--       NULL;  
--     END IF;
-- END;
-- /
